// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function OpenVault(arg1) {
    return window['go']['main']['App']['OpenVault'](arg1);
}

export function ListNotes(arg1) {
    return window['go']['main']['App']['ListNotes'](arg1);
}

export function ReadNote(arg1) {
    return window['go']['main']['App']['ReadNote'](arg1);
}

export function CreateNote(arg1, arg2, arg3) {
    return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3);
}

export function UpdateNote(arg1, arg2, arg3, arg4) {
    return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3, arg4);
}

export function DeleteNote(arg1) {
    return window['go']['main']['App']['DeleteNote'](arg1);
}

export function MoveNote(arg1, arg2) {
    return window['go']['main']['App']['MoveNote'](arg1, arg2);
}

export function ExportHTML(arg1) {
    return window['go']['main']['App']['ExportHTML'](arg1);
}

export function RenderMarkdown(arg1) {
    return window['go']['main']['App']['RenderMarkdown'](arg1);
}

export function Backlinks(arg1) {
    return window['go']['main']['App']['Backlinks'](arg1);
}

export function ResolveWikilink(arg1) {
    return window['go']['main']['App']['ResolveWikilink'](arg1);
}

export function Search(arg1) {
    return window['go']['main']['App']['Search'](arg1);
}

export function GetStartupState() {
    return window['go']['main']['App']['GetStartupState']();
}

export function RecentVaults() {
    return window['go']['main']['App']['RecentVaults']();
}

export function CreateVault(arg1) {
    return window['go']['main']['App']['CreateVault'](arg1);
}

export function OpenInNewWindow(arg1) {
    return window['go']['main']['App']['OpenInNewWindow'](arg1);
}
