// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface NoteMeta {
    ID: string;
    Title: string;
    Tags: string[] | null;
    Frontmatter: Record<string, unknown> | null;
    ModTime: string;
}

export interface Note extends NoteMeta {
    Body: string;
    ETag: string;
}

export interface VaultInfo {
    path: string;
}

export function Greet(arg1: string): Promise<string>;
export function OpenVault(arg1: string): Promise<VaultInfo>;
export function ListNotes(arg1: string): Promise<NoteMeta[]>;
export function ReadNote(arg1: string): Promise<Note>;
