// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface NoteMeta {
    ID: string;
    Title: string;
    Tags: string[] | null;
    Frontmatter: Record<string, unknown> | null;
    ModTime: string;
    Snippet: string;
}

export interface Note extends NoteMeta {
    Body: string;
    ETag: string;
}

export interface VaultInfo {
    path: string;
}

export interface StartupState {
    vaultPath: string;
    vaultError: string;
    recent: string[];
}

export function Greet(arg1: string): Promise<string>;
export function GetStartupState(): Promise<StartupState>;
export function OpenVault(arg1: string): Promise<VaultInfo>;
export function ListNotes(arg1: string): Promise<NoteMeta[]>;
export function ReadNote(arg1: string): Promise<Note>;
export function CreateNote(arg1: string, arg2: string, arg3: Record<string, unknown> | null): Promise<Note>;
export function UpdateNote(arg1: string, arg2: string, arg3: Record<string, unknown> | null, arg4: string): Promise<Note>;
export function DeleteNote(arg1: string): Promise<void>;
export function MoveNote(arg1: string, arg2: string): Promise<void>;
export function ExportHTML(arg1: string): Promise<string>;
export function RenderMarkdown(arg1: string): Promise<string>;
export function Backlinks(arg1: string): Promise<NoteMeta[]>;
export function ResolveWikilink(arg1: string): Promise<string>;
export function Search(arg1: string): Promise<NoteMeta[]>;
export function RecentVaults(): Promise<string[]>;
export function CreateVault(arg1: string): Promise<VaultInfo>;
export function OpenInNewWindow(arg1: string): Promise<void>;
