// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function OpenVault(arg1) {
    return window['go']['main']['App']['OpenVault'](arg1);
}

export function ListNotes(arg1) {
    return window['go']['main']['App']['ListNotes'](arg1);
}

export function ReadNote(arg1) {
    return window['go']['main']['App']['ReadNote'](arg1);
}
