// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {main} from '../models';

export function Backlinks(arg1:string):Promise<Array<core.NoteMeta>>;

export function CreateNote(arg1:string,arg2:string,arg3:Record<string, any>):Promise<core.Note>;

export function CreateVault(arg1:string):Promise<main.VaultInfo>;

export function DeleteNote(arg1:string):Promise<void>;

export function ExportHTML(arg1:string):Promise<string>;

export function GetStartupState():Promise<main.StartupState>;

export function ListNotes(arg1:string):Promise<Array<core.NoteMeta>>;

export function MoveNote(arg1:string,arg2:string):Promise<void>;

export function OpenInNewWindow(arg1:string):Promise<void>;

export function OpenVault(arg1:string):Promise<main.VaultInfo>;

export function ReadNote(arg1:string):Promise<core.Note>;

export function RecentVaults():Promise<Array<string>>;

export function RenderMarkdown(arg1:string):Promise<string>;

export function ResolveWikilink(arg1:string):Promise<string>;

export function Search(arg1:string):Promise<Array<core.NoteMeta>>;

export function UpdateNote(arg1:string,arg2:string,arg3:Record<string, any>,arg4:string):Promise<core.Note>;
